version: '2'
services:
  elasticsearch:
    ports:
        - 9200:9200
    image: elasticsearch:5.5.1

  kibana:
    image: kibana:5.5.1
    ports:
        - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200/
    links:
      - elasticsearch

  pilot:
    image: log-pilot:latest
    volumes:
      - /etc/localtime:/etc/localtime
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/host:ro
    cap_add:
      - SYS_ADMIN
    environment:
      LOGGING_OUTPUT: elasticsearch
      ELASTICSEARCH_HOSTS: elasticsearch:9200
    links:
      - elasticsearch
